---
title: "tidy"
output: html_document
---

```{r}
# Get the Data
library(tidyverse)
# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2021-03-16')
tuesdata <- tidytuesdayR::tt_load(2021, week = 12)

games <- tuesdata$games

# Or read in the data manually

games <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-16/games.csv')


```
```{r}
games
library(scales)
library(lubridate)
```

```{r}
games%>%
  count(gamename)
games<-games%>%
  mutate(date = ymd(paste(year,month,1)))%>%
  mutate(month = fct_reorder(month,month(date)))
```

```{r}
# # of games measured
games%>%
  count(date)%>%
  ggplot(aes(date,n))+
  geom_col()

```


```{r}
#Average number of players at the same time by date
games%>%
  group_by(date)%>%
  ggplot(aes(date,avg))+
  geom_col()
```







